### ISSUE TITLE
.Site.Copyright for Copyright 

### ISSUE THREAD

**Issue by nobu-k** [Tazeg/hugo-blog-jeffprod#3]
In [footer](https://github.com/Tazeg/hugo-blog-jeffprod/blob/2d097b9818d3848d9ed7ebac5e3d39e3e58a7b21/layouts/partials/footer.html), `.Site.Title` is used to show the name for copyright. However, [`.Site.Copyright`](https://gohugo.io/variables/site/#site-variables-list) seems the right parameter for it. What do you think?

**Comment by Tazeg** [comment]
Thats right, in the `config.toml` you should add `copyright = "my copyright"` and replace `.Site.Title` with `.Site.Copyright` in `layouts/partials/footer.html`.

I did'nt do it because the demo theme at https://themes.gohugo.io/theme/hugo-blog-jeffprod/ would show nothing as by default, there is no variable `copyright` in the default config file.

**Comment by nobu-k** [comment]
I see. It looks pretty complex to support `.Site.Copyright` properly. Also, I've misunderstood how it should work. I thought it was only for the name shown in copyright but it should probably contain all the text for copyright as implemented in  https://github.com/MunifTanjim/minimo/blob/master/layouts/partials/footer/copyright.html . I doubt other themes support it in a consistent way.

I'll make a local change as you suggested for now. Thank you for your answer and providing a cool theme!
